### ISSUE TITLE
New Waveshare device model file = epd4in2_V2.py

### ISSUE THREAD

**Issue by DavidMeermans** [aceisace/Inkycal#189]
When using Inkycal with a Waveshare 4.2 inch V2, color display, Inkycal does not display--screen remains blank without indication of activity.  Waveshare-provided C, Python, and Python3 test applications all run successfully.

[epd4in2b_V2.py.txt](https://github.com/aceisace/Inkycal/files/6366243/epd4in2b_V2.py.txt)

![Waveshare 4in2V2](https://user-images.githubusercontent.com/62485963/115890850-03d07f00-a41b-11eb-8efc-379a982f44ef.jpg)

**Comment by aceisace** [comment]
Thanks for the issue @DavidMeermans 
As per your code suggestion, the change at line 51 from 10 to 5 ms has been officially implemented in the main repo as part of a hotfix: https://github.com/aceisace/Inkycal/commit/f2a79dac2fb9c1ae2ea22a7d72964670e77a7274

Any further installations of Inkycal should now not need any medifications. 

I'll be closing this issue now since it has been resolved. Should you feel a need to re-open this issue, please feel free to do so.
